apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l2n0v91o8-java-quarkus
  janus-idp.io/tekton: l2n0v91o8-java-quarkus
  backstage.io/kubernetes-id: l2n0v91o8-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l2n0v91o8-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
